@MinimalApi_HostAddress = http://localhost:5189

GET {{MinimalApi_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{MinimalApi_HostAddress}}/movies
Accept: application/json

###

@movieId = 4b587cf1-f2c6-47a6-9a07-47bbe5cba025
GET {{MinimalApi_HostAddress}}/movies/{{movieId}}
Accept: application/json

###

POST {{MinimalApi_HostAddress}}/movies
Content-Type: application/json
{
  "title": "Kruty",
  "DirectorName":"Olexyi Shaparev",
  "ReleaseYear": 2018
}

###
@movieToUpdateId = a6d9b7ac-0c1e-45da-8a0c-f326594146a1
PUT {{MinimalApi_HostAddress}}/movies/{{movieToUpdateId}}
Content-Type: application/json
{
  "title": "Kruty",
  "DirectorName": Olexyi Shaparev",
  "ReleaseYear": 2018
}

###
@movieToDeleteId = aaa27ce5-f7a9-4ae7-8475-aec360b1d8d5
DELETE {{MinimalApi_HostAddress}}/movies/{{movieToDeleteId}}
